### PR TITLE
Adding custom.sh to implement Mark Jordan's islandora_scg (Sample …

### PR DESCRIPTION
**Pull request by McFateM**
…Content Generator) module.

### CODE REVIEW

**Comment by patdunlavey** [comment]
I asked Gavin Morris to review, since he's our vagrant guy.

**Comment by patdunlavey** [comment]
Gavin says he sees little potential harm in this pull request, but does not have time for testing. @McFateM I'll give you the last word. Are you comfortable with having this merged

**Comment by McFateM** [comment]
Yes, I’m confident the changes made thus far will work and not interrupt anything.  Peter also tried this before the very latest changes and it worked for him too.

Once this pull is merged I’ll clone the repo again and give it one more quick test (before adding even more goodies!).

—Mark

**Comment by patdunlavey** [comment]
Ok, merged!

**Comment by McFateM** [comment]
Thanks.  I did a quick\* test and all seems to be working as it should.   *'vagrant_destroy' and a subsequent 'vagrant_up' took about 25 minutes from start-to-finish on my MacBook Air.

**Pull request merged**
