### PR TITLE
Updates from Islandora-Labs and introduction of custom.sh extensions.

### PR DESCRIPTION
**Pull request by McFateM**
This pull incorporates updates made to islandora_vagrant by Nick Ruest at Islandora Labs.  It also introduces the concept of "extending" the VM without making any changes to the original.  This is achieved by introducing a custom.sh script along with a new ./scripts/custom directory (to hold additional extensions) and ./configs/custom_variables script (to control the /custom scripts).

### CODE REVIEW

**Comment by patdunlavey** [comment]
Thanks Mark!

**Comment by br2490** [comment]
Did anyone else test before this PR was merged?

**Comment by McFateM** [comment]
Peter MacDonald (Hamilton College) and I were both successful in doing a 'vagrant up' followed by multiple 'vagrant provision' operations.   I have to admit that the merge process was pretty clunky (my own fault as a Git noob, big thanks to Pat Dunlavey for his patience and assistance!) but I believe the project is intact and still manageable.  I destroyed my VM a short time ago and just completed a 'vagrant up' from my local repo, which should be in-sync with Islandora-Collaboration-Group/islandora_vagrant, and it's working nicely.

-Mark

**Comment by br2490** [comment]
McFateM++ Thank you, **great code** and PR.
@patdunlavey ty for merge.

I think in the future we should be mindful of including 'tested working' since we're relying one another to provide feedback. 
I was just able to vagrant up as well ;)

**Pull request merged**
